"""The timing kernel's cross-language contract: five JSON files, generated from the registries.

The contract lives in ``an/data/timing/`` (shipped in the wheel) and is what any
other implementation of the kernel — the TypeScript one, a package that copies
`an`'s track format — copies and asserts:

=========================  ====================================================
``easing.json``            every registered easing (name, version, family,
                           solver) with sample values, plus parametrised examples
``kinds.json``             every field kind with sample interpolations, and the
                           seeded property spaces
``timeline.schema.json``   the authored flat timeline ``(start, end, address, change)``
``compiled.schema.json``   tracks, placed clips, loop modes, channels — the
                           compiled form ``runtime.js`` consumes
``timing_vectors.json``    compiled documents and the state at listed times
=========================  ====================================================

**Numbers agree within** ``1e-9 * max(1, |x|, |y|)``; strings, booleans,
``null``, list lengths and object keys agree exactly. A state is SPARSE: an
address no clip has started writing is absent (at rest).

The files are regenerated by ``python -m an.timing.contract write`` and checked
by ``python -m an.timing.contract check`` (a test runs the check). Regenerating
is a deliberate act: a change to a committed sample is a change of the contract.

>>> doc = {"timeline": {"duration": 1.0, "tracks": [{"clips": [
...     {"animation_id": "m", "start_time": 0.0}]}]},
...     "animations": {"m": {"duration": 1.0, "channels": [{"target": "cam",
...     "property": "yaw", "keyframes": [{"time": 0.0, "value": 350.0},
...     {"time": 1.0, "value": 10.0}]}]}}}
>>> space = {"fields": [{"pattern": "yaw", "spec": {"kind": "angle"}}]}
>>> state_at(doc, 0.5, space=space)
{'cam:yaw': 360.0}
"""

from __future__ import annotations

import json
import math
import sys
from dataclasses import fields
from pathlib import Path
from typing import Any, Mapping

from an.timing import _vectors
from an.timing.address import format_address
from an.timing.clip import LoopMode
from an.timing.easing import (
    CORE_OWNER,
    CSS_BEZIERS,
    EASING_FAMILIES,
    STEP_POSITIONS,
    apply_easing,
    easing_entries,
    solvers,
)
from an.timing.flat import CHANGE_KINDS, FLAT_TIMELINE_FORMAT, FLAT_TIMELINE_VERSION
from an.timing.kinds import (
    AngleKind,
    ColorKind,
    DiscreteKind,
    NumberKind,
    OrbitKind,
    QuaternionKind,
    Segment,
    VectorKind,
    kind_from_spec,
)
from an.timing.spaces import (
    VALUE_TYPED,
    PropertySpace,
    get_space,
    space_from_json,
    space_names,
)
from an.timing.timeline import evaluate_timeline, timeline_from_compiled

#: Where the committed contract files live (inside the package, so they ship).
CONTRACT_DIR: Path = Path(__file__).resolve().parents[1] / "data" / "timing"
CONTRACT_VERSION: int = 1
#: The contract's tolerance: |x - y| <= REL_TOL * max(1, |x|, |y|).
REL_TOL: float = 1e-9
EASING_SAMPLE_STEPS: int = 20
JSON_SCHEMA_DIALECT: str = "https://json-schema.org/draft/2020-12/schema"
SCHEMA_ID_ROOT: str = (
    "https://raw.githubusercontent.com/thorwhalen/an/main/an/data/timing/"
)

EASING_FILE = "easing.json"
KINDS_FILE = "kinds.json"
TIMELINE_SCHEMA_FILE = "timeline.schema.json"
COMPILED_SCHEMA_FILE = "compiled.schema.json"
VECTORS_FILE = "timing_vectors.json"
CONTRACT_FILES: tuple[str, ...] = (
    EASING_FILE,
    KINDS_FILE,
    TIMELINE_SCHEMA_FILE,
    COMPILED_SCHEMA_FILE,
    VECTORS_FILE,
)


# -----------------------------------------------------------------------------
# Evaluation in contract terms
# -----------------------------------------------------------------------------


def _jsonable(value: Any) -> Any:
    if isinstance(value, tuple):
        return [_jsonable(v) for v in value]
    if isinstance(value, list):
        return [_jsonable(v) for v in value]
    if isinstance(value, dict):
        return {k: _jsonable(v) for k, v in value.items()}
    return value


def resolve_space(space: str | Mapping[str, Any] | PropertySpace) -> PropertySpace:
    """A vector case's ``space``: a registered space's name, or its JSON form."""
    if isinstance(space, PropertySpace):
        return space
    if isinstance(space, str):
        return get_space(space)
    return space_from_json(space)


def state_at(doc: Mapping[str, Any], t: float, *, space: Any) -> dict[str, Any]:
    """The sparse state of compiled document ``doc`` at ``t``, keyed by address."""
    pose = evaluate_timeline(timeline_from_compiled(doc), t, space=resolve_space(space))
    return {
        format_address(target, prop): _jsonable(v) for (target, prop), v in pose.items()
    }


def values_close(expected: Any, actual: Any, *, rel_tol: float = REL_TOL) -> bool:
    """The contract's comparison (see the module docstring).

    >>> values_close(1e9, 1e9 + 0.5), values_close([1, "a"], [1.0, "a"]), values_close(True, 1)
    (True, True, False)
    """
    if isinstance(expected, bool) or isinstance(actual, bool):
        return type(expected) is type(actual) and expected == actual
    if isinstance(expected, (int, float)) and isinstance(actual, (int, float)):
        if math.isnan(expected) or math.isnan(actual):
            return math.isnan(expected) and math.isnan(actual)
        return abs(expected - actual) <= rel_tol * max(1.0, abs(expected), abs(actual))
    if isinstance(expected, list) and isinstance(actual, list):
        return len(expected) == len(actual) and all(
            values_close(e, a, rel_tol=rel_tol) for e, a in zip(expected, actual)
        )
    if isinstance(expected, dict) and isinstance(actual, dict):
        return expected.keys() == actual.keys() and all(
            values_close(expected[k], actual[k], rel_tol=rel_tol) for k in expected
        )
    return expected == actual


#: The cases whose space is the value-typed rule's write-group space are ALSO
#: evaluated with ``space=VALUE_TYPED`` — the rule ``runtime.js`` implements —
#: so both rules are held to the same numbers (the default, ``space=None``, is
#: the declared rule since an#239 item 2).
VALUE_TYPED_CASE_SPACE: str = "stage.node"


def _state_value_typed(doc: Mapping[str, Any], t: float) -> dict[str, Any]:
    pose = evaluate_timeline(timeline_from_compiled(doc), t, space=VALUE_TYPED)
    return {format_address(tg, pr): _jsonable(v) for (tg, pr), v in pose.items()}


def check_vectors(vectors: Mapping[str, Any] | None = None) -> list[str]:
    """Every sample of ``vectors`` (default: the committed file) that ``an.timing``
    does not reproduce, as one line each. Empty means the kernel meets the contract.

    Both evaluation rules are held: every case under its declared space, and every
    ``stage.node`` case also under the value-typed rule (``space=VALUE_TYPED``)."""
    if vectors is None:
        vectors = load_contract_file(VECTORS_FILE)
    problems = []
    for case in vectors["cases"]:
        rules = [
            ("declared", lambda doc, t, sp=case["space"]: state_at(doc, t, space=sp))
        ]
        if case["space"] == VALUE_TYPED_CASE_SPACE:
            rules.append(("value-typed", _state_value_typed))
        for rule, evaluate in rules:
            for sample in case["samples"]:
                got = evaluate(case["document"], sample["t"])
                if not values_close(sample["state"], got):
                    problems.append(
                        f"{case['name']} ({rule}) at t={sample['t']!r}: "
                        f"expected {sample['state']}, got {got}"
                    )
    return problems


# -----------------------------------------------------------------------------
# The five files
# -----------------------------------------------------------------------------


#: Where every easing is sampled: a uniform grid, plus points that reach the
#: solvers' fallbacks (near the ends, and around the middle of a curve whose
#: slope vanishes there, e.g. cubic-bezier(1, 0, 0, 1)).
SOLVER_PROBE_U: tuple[float, ...] = (1e-6, 0.4, 0.501, 1 - 1e-6)
SAMPLE_U: tuple[float, ...] = tuple(
    sorted(
        {i / EASING_SAMPLE_STEPS for i in range(EASING_SAMPLE_STEPS + 1)}
        | set(SOLVER_PROBE_U)
    )
)


def _easing_samples(spec: Any) -> list[float]:
    return [apply_easing(spec, u) for u in SAMPLE_U]


#: Parametrised specs the easing file samples, beside the named entries.
PARAMETRIC_EXAMPLES: tuple[Any, ...] = (
    "cubic-bezier(0.25, 0.1, 0.25, 1)",
    "cubic-bezier(0.5, -0.8, 0.5, 1.8)",
    "cubic-bezier(0.3, 1.8, 0.7, -0.8)",
    "steps(4)",
    "steps(4, jump-start)",
    "steps(3, jump-none)",
    "steps(2, jump-both)",
    "steps(2, start)",
    "cubic-bezier(1, 0, 0, 1)",  # Newton stalls mid-curve: the bisection runs
    [0.42, 0.0, 0.58, 1.0],
    [0.5, 2.0, 0.5, 2.0],
    [0.3, 3.0, 0.7, 0.0],
    [1.0, 0.0, 0.0, 1.0],  # the legacy solver's slope guard and clamps
    [0.42, 0.0, 1.0, 1.0],
    [0.0, 0.0, 0.58, 1.0],
)

#: How a CSS-named document's names map onto this registry where the name means
#: something else here. ``ease`` is `an`'s quadratic (ADR 0001 decision 10,
#: amended 2026-10-01); a CSS document's ``ease`` is this spec.
CSS_IMPORT_ALIASES: dict[str, str] = {"ease": "cubic-bezier(0.25, 0.1, 0.25, 1)"}


def build_easing() -> dict[str, Any]:
    return {
        "format": "an.timing.easing",
        "version": CONTRACT_VERSION,
        "description": (
            "Every named easing, the solver that computes it, and its value at "
            "u in 'sample_u'. Hyphenated CSS names are the exact CSS "
            "curves; an's underscore names (and 'ease') are an's own polynomial "
            "curves, so a CSS document's 'ease' must be read through "
            "'css_import_aliases'; Manim's rate functions keep Manim's names. A bare 4-number "
            "list is a cubic Bezier solved by 'an-bezier-newton-8'; the string "
            "'cubic-bezier(...)' is solved by 'css-bezier-newton-bisection'."
        ),
        "families": list(EASING_FAMILIES),
        "solvers": solvers(owner=CORE_OWNER),
        "css_hyphenated_curves": {
            k: list(v) for k, v in CSS_BEZIERS.items() if k not in CSS_IMPORT_ALIASES
        },
        "css_import_aliases": dict(CSS_IMPORT_ALIASES),
        "step_positions": list(STEP_POSITIONS),
        "sample_u": list(SAMPLE_U),
        "entries": [
            {**e.to_json(), "samples": _easing_samples(e.name)}
            for e in easing_entries(owner=CORE_OWNER)
        ],
        "parametric": [
            {
                "spec": spec,
                "solver": (
                    "an-bezier-newton-8"
                    if isinstance(spec, list)
                    else "css-steps"
                    if spec.startswith("steps")
                    else "css-bezier-newton-bisection"
                ),
                "samples": _easing_samples(spec),
            }
            for spec in PARAMETRIC_EXAMPLES
        ],
    }


def _kind_samples(kind: Any, a: Any, b: Any, us: tuple[float, ...]) -> list[dict]:
    return [
        {
            "a": a,
            "b": b,
            "u": u,
            "value": _jsonable(kind.interpolate(a, b, u, Segment(u, 0.0, 1.0))),
        }
        for u in us
    ]


def _discrete_samples(
    kind: DiscreteKind, start: float, end: float, ts: list[float]
) -> list[dict]:
    return [
        {
            "a": "A",
            "b": "B",
            "segment": [start, end],
            "t": t,
            "value": kind.interpolate("A", "B", 0.0, Segment(t, start, end)),
        }
        for t in ts
    ]


def build_kinds() -> dict[str, Any]:
    us = (0.0, 0.25, 0.5, 0.75, 1.0, 1.25)
    quarter = [0.0, 0.25, 0.5, 0.75, math.nextafter(1.0, 0.0)]
    examples = [
        (NumberKind(), -2.0, 3.0, us),
        (NumberKind(space="log"), 1.0, 4.0, us),
        (AngleKind(), 350.0, 10.0, us),
        (AngleKind(), 10.0, 350.0, us[:5]),
        (AngleKind(unit="rad"), 0.1, 6.1, us[:5]),
        (AngleKind(wrap=False), 0.0, 720.0, us[:5]),
        (VectorKind(), [0.0, 0.0, 0.0], [1.0, -2.0, 4.0], us[:5]),
        (QuaternionKind(), [0.0, 0.0, 0.0, 1.0], [-0.5, -0.5, -0.5, -0.5], us[:5]),
        (ColorKind(), "#ff0000", "#00ff00", us[:5]),
        (ColorKind(), [0.2, 0.4, 0.6], [1.0, 0.5, 0.0, 0.5], us[:5]),
        (ColorKind(space="srgb"), "#ff0000", "#0000ff80", us[:5]),
        (
            OrbitKind(),
            {
                "azimuth": 340.0,
                "elevation": 10.0,
                "distance": 2.0,
                "target": [0.0, 0.0, 0.0],
                "projection": "perspective",
            },
            {
                "azimuth": 30.0,
                "elevation": 60.0,
                "distance": 8.0,
                "target": [1.0, 2.0, 3.0],
                "projection": "orthographic",
            },
            us[:5],
        ),
    ]
    by_kind: dict[str, list[dict]] = {}
    for kind, a, b, u_list in examples:
        by_kind.setdefault(kind.name, []).append(
            {"spec": kind.to_spec(), "samples": _kind_samples(kind, a, b, u_list)}
        )
    by_kind["discrete"] = [
        {
            "spec": DiscreteKind().to_spec(),
            "samples": _discrete_samples(DiscreteKind(), 0.0, 1.0, quarter),
        },
        {
            "spec": DiscreteKind(switch_at=0.25).to_spec(),
            "samples": _discrete_samples(
                DiscreteKind(switch_at=0.25), 2.0, 4.0, [2.0, 2.49, 2.5, 3.0]
            ),
        },
        {
            "spec": DiscreteKind(switch_at=1).to_spec(),
            "note": "switch_at == 1 is t >= b.time with no arithmetic: at the float below "
            "b.time, (t - a.time) / span rounds to 1.0 and the value is still 'A'",
            "samples": _discrete_samples(
                DiscreteKind(switch_at=1),
                _vectors.BOUNDARY_A,
                _vectors.BOUNDARY_B,
                [
                    _vectors.BOUNDARY_A,
                    5.0,
                    math.nextafter(_vectors.BOUNDARY_B, 0.0),
                    _vectors.BOUNDARY_B,
                ],
            ),
        },
    ]
    kinds = []
    for name in by_kind:
        factory = kind_from_spec(name)
        kinds.append(
            {
                "kind": name,
                "description": (type(factory).__doc__ or "").strip().split("\n\n")[0],
                "params": {f.name: getattr(factory, f.name) for f in fields(factory)},
                "examples": by_kind[name],
            }
        )
    return {
        "format": "an.timing.kinds",
        "version": CONTRACT_VERSION,
        "description": (
            "Each field kind's parameters (with defaults) and sample interpolations. "
            "'u' is the eased progress handed to the kind; a discrete kind ignores it "
            "and switches on time t in 'segment' = [a.time, b.time). An undeclared "
            "property is {'kind': 'discrete'} (switch_at 0.5)."
        ),
        "kinds": kinds,
        "spaces": [get_space(n).to_json() for n in space_names(owner=CORE_OWNER)],
    }


_EASING_SPEC_SCHEMA: dict[str, Any] = {
    "description": (
        "null (linear), a name or parametrised spec from easing.json, or a 4-number "
        "cubic-Bezier control list solved by an's legacy solver. The schema does "
        "NOT check names (the registry is open); an evaluator refuses an unknown one"
    ),
    "anyOf": [
        {"type": "null"},
        {"type": "string", "minLength": 1},
        {"type": "array", "items": {"type": "number"}, "minItems": 4, "maxItems": 4},
    ],
}

#: The address grammar as a regular expression (the parser is ``an.timing.address``).
ADDRESS_PATTERN: str = r"^[^:/@\s](?:[^:/@]*[^:/@\s])?(?:/[^:/@\s](?:[^:/@]*[^:/@\s])?)*:[^:/@.\s](?:[^:/@.]*[^:/@.\s])?(?:\.[^:/@.\s](?:[^:/@.]*[^:/@.\s])?)*(?:@[^:/@\s](?:[^:/@]*[^:/@\s])?)?$"


def build_timeline_schema() -> dict[str, Any]:
    return {
        "$schema": JSON_SCHEMA_DIALECT,
        "$id": SCHEMA_ID_ROOT + TIMELINE_SCHEMA_FILE,
        "title": "an flat timeline",
        "description": (
            "The authored flat timeline: every action at absolute seconds, as "
            "(start, end, address, change). A change is 'set' or 'tween'; a tween "
            "without 'from' starts from whatever the property has at 'start'."
        ),
        "type": "object",
        "required": ["format", "version", "actions"],
        "properties": {
            "format": {"const": FLAT_TIMELINE_FORMAT},
            "version": {"const": FLAT_TIMELINE_VERSION},
            "duration": {"type": "number", "minimum": 0},
            "actions": {"type": "array", "items": {"$ref": "#/$defs/action"}},
        },
        "$defs": {
            "address": {
                "type": "string",
                "pattern": ADDRESS_PATTERN,
                "description": "<entity>[/<node>...]:<field>[@<qualifier>]; the field may be dotted",
            },
            "easing": _EASING_SPEC_SCHEMA,
            "action": {
                "type": "object",
                "required": ["start", "end", "address", "change"],
                "additionalProperties": False,
                "properties": {
                    "start": {"type": "number"},
                    "end": {"type": "number"},
                    "address": {"$ref": "#/$defs/address"},
                    "change": {"$ref": "#/$defs/change"},
                },
            },
            "change": {
                "oneOf": [
                    {
                        "type": "object",
                        "required": ["kind", "value"],
                        "additionalProperties": False,
                        "properties": {"kind": {"const": CHANGE_KINDS[0]}, "value": {}},
                    },
                    {
                        "type": "object",
                        "required": ["kind", "to", "easing"],
                        "additionalProperties": False,
                        "description": (
                            "'easing' is always written, resolved (null = linear); an "
                            "absent 'from' means from the value the property has at start"
                        ),
                        "properties": {
                            "kind": {"const": CHANGE_KINDS[1]},
                            "from": {},
                            "to": {},
                            "easing": {"$ref": "#/$defs/easing"},
                        },
                    },
                ]
            },
        },
    }


def build_compiled_schema() -> dict[str, Any]:
    number = {"type": "number"}
    nonneg = {"type": "number", "minimum": 0}
    return {
        "$schema": JSON_SCHEMA_DIALECT,
        "$id": SCHEMA_ID_ROOT + COMPILED_SCHEMA_FILE,
        "title": "an compiled timeline",
        "description": (
            "The compiled evaluation form, as runtime.js consumes it: tracks of "
            "placed clips (a clip is active on [start, end] inclusive; later wins by "
            "track then clip order; an ended clip's final value holds; an unstarted "
            "property is at rest and absent), clips with a loop mode, channels of "
            "keyframes (half-open segments, easing on the leaving key). Other "
            "top-level members (an engine's scene tree) are allowed."
        ),
        "type": "object",
        "required": ["timeline", "animations"],
        "properties": {
            "timeline": {"$ref": "#/$defs/timeline"},
            "animations": {
                "type": "object",
                "additionalProperties": {"$ref": "#/$defs/animation"},
            },
        },
        "$defs": {
            "easing": _EASING_SPEC_SCHEMA,
            "timeline": {
                "type": "object",
                "required": ["duration"],
                "additionalProperties": False,
                "properties": {
                    "duration": nonneg,
                    "tracks": {"type": "array", "items": {"$ref": "#/$defs/track"}},
                },
            },
            "track": {
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "target_root": {"type": "string"},
                    "clips": {
                        "type": "array",
                        "items": {"$ref": "#/$defs/placed_clip"},
                    },
                },
            },
            "placed_clip": {
                "type": "object",
                "required": ["animation_id"],
                "additionalProperties": False,
                "properties": {
                    "animation_id": {"type": "string"},
                    "start_time": number,
                    "duration": {
                        "anyOf": [
                            {"type": "null"},
                            {"type": "number", "exclusiveMinimum": 0},
                        ]
                    },
                    "speed": {"type": "number", "exclusiveMinimum": 0},
                    "blend_in": nonneg,
                    "blend_out": nonneg,
                },
            },
            "animation": {
                "type": "object",
                "required": ["duration"],
                "additionalProperties": False,
                "properties": {
                    "name": {"type": "string"},
                    "duration": {"type": "number", "exclusiveMinimum": 0},
                    "loop_mode": {"enum": [m.value for m in LoopMode]},
                    "channels": {"type": "array", "items": {"$ref": "#/$defs/channel"}},
                },
            },
            "channel": {
                "type": "object",
                "required": ["target", "property", "keyframes"],
                "additionalProperties": False,
                "properties": {
                    "target": {"type": "string", "minLength": 1},
                    "property": {"type": "string", "minLength": 1},
                    "keyframes": {
                        "type": "array",
                        "minItems": 1,
                        "items": {"$ref": "#/$defs/keyframe"},
                    },
                },
            },
            "keyframe": {
                "type": "object",
                "required": ["time", "value"],
                "additionalProperties": False,
                "properties": {
                    "time": number,
                    "value": {},
                    "easing": {"$ref": "#/$defs/easing"},
                },
            },
        },
    }


def build_vectors() -> dict[str, Any]:
    out_cases = []
    for case in _vectors.cases():
        samples = [
            {"t": t, "state": state_at(case["document"], t, space=case["space"])}
            for t in case["times"]
        ]
        out_cases.append(
            {
                "name": case["name"],
                "description": case["description"],
                "origin": case["origin"],
                "space": case["space"],
                "document": case["document"],
                "samples": samples,
            }
        )
    return {
        "format": "an.timing.vectors",
        "version": CONTRACT_VERSION,
        "description": (
            "For each case, the sparse state an implementation of the timing kernel "
            "must return at each listed time, for a compiled document "
            "(compiled.schema.json) under a property space (a registered name from "
            "kinds.json, or inline). States are keyed by address (target:property); "
            "an address no clip has started is absent. Numbers agree within "
            f"{REL_TOL} * max(1, |x|, |y|); everything else exactly. 'stage.node' "
            "cases use only the stage's easings and are also what runtime.js "
            "evaluates. Sample times include every clip and keyframe boundary and "
            "every midpoint between them."
        ),
        "tolerance": {"relative": REL_TOL, "floor": 1.0},
        "cases": out_cases,
    }


def build_contract() -> dict[str, Any]:
    """Every contract file's content, by file name, generated from the registries."""
    return {
        EASING_FILE: build_easing(),
        KINDS_FILE: build_kinds(),
        TIMELINE_SCHEMA_FILE: build_timeline_schema(),
        COMPILED_SCHEMA_FILE: build_compiled_schema(),
        VECTORS_FILE: build_vectors(),
    }


def dumps(obj: Any) -> str:
    """The committed text of a contract file (stable, diffable)."""
    return json.dumps(obj, indent=1, ensure_ascii=False, allow_nan=False) + "\n"


def load_contract_file(name: str, *, directory: Path = CONTRACT_DIR) -> Any:
    return json.loads((directory / name).read_text(encoding="utf-8"))


def write_contract(directory: Path = CONTRACT_DIR) -> list[Path]:
    """Regenerate every contract file under ``directory``."""
    directory.mkdir(parents=True, exist_ok=True)
    written = []
    for name, obj in build_contract().items():
        path = directory / name
        path.write_text(dumps(obj), encoding="utf-8")
        written.append(path)
    return written


def contract_drift(directory: Path = CONTRACT_DIR) -> list[str]:
    """How the committed files differ from what the registries generate today.

    Numbers compare with the contract's tolerance, because a transcendental
    function (``exp``, ``sin``, ``pow``) may differ in its last bit across
    platforms' maths libraries; anything else must match exactly.
    """
    drift = []
    for name, built in build_contract().items():
        path = directory / name
        if not path.exists():
            drift.append(f"{name}: missing")
            continue
        committed = json.loads(path.read_text(encoding="utf-8"))
        if not values_close(committed, _jsonable(json.loads(dumps(built)))):
            drift.append(f"{name}: differs from what the registries generate")
        if name == VECTORS_FILE:
            names = lambda doc: {c["name"] for c in doc.get("cases", ())}  # noqa: E731
            removed = sorted(names(committed) - names(built))
            if removed:
                drift.append(f"{name}: cases removed: {removed}")
    return drift


def main(argv: list[str] | None = None) -> int:
    """``python -m an.timing.contract [write|check]``."""
    args = sys.argv[1:] if argv is None else argv
    command = args[0] if args else "check"
    if command == "write":
        for path in write_contract():
            print(f"wrote {path.name}")
        return 0
    if command == "check":
        problems = contract_drift() + check_vectors()
        for line in problems:
            print(line)
        return 1 if problems else 0
    print(f"usage: python -m an.timing.contract [write|check]; got {command!r}")
    return 2


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
