"""The vocabulary section of the downstream ``an`` skill, generated from the registry.

ADR 0003 decision 6's third generated surface. The skill keeps its prose; the
table between the two markers is rendered here and checked by a test, so a
preset, a method or a version cannot change without the skill saying so::

    python -m an.semantic.docs --write .claude/skills/an/SKILL.md

>>> "| `walk` |" in skill_vocabulary_section() or "| `tween` |" in skill_vocabulary_section()
True
"""

from __future__ import annotations

import sys
from pathlib import Path

from an.semantic.entries import LEVELS, Entry, Method
from an.semantic.registry import aspects, entries, methods_of

__all__ = [
    "BEGIN_MARKER",
    "END_MARKER",
    "replace_section",
    "skill_vocabulary_section",
]

BEGIN_MARKER: str = "<!-- vocabulary:begin (generated by `python -m an.semantic.docs --write`; do not edit) -->"
END_MARKER: str = "<!-- vocabulary:end -->"

#: Kinds listed in the skill, in order, with their headings.
SKILL_KINDS: tuple[tuple[str, str], ...] = (
    ("action", "Action kinds"),
    ("entity", "Entity kinds"),
    ("motion_preset", "Motion presets"),
    ("expression_preset", "Expression presets"),
    ("camera_move", "Camera moves"),
)


def _cell(text: str) -> str:
    return (text or "").replace("|", "\\|").replace("\n", " ")


def _levels(e: Entry) -> str:
    return ", ".join(lv for lv in LEVELS if lv in e.levels)


def _table(found: tuple[Entry, ...]) -> list[str]:
    rows = ["| Name | Version | Levels | What it is |", "|---|---|---|---|"]
    for e in found:
        rows.append(
            f"| `{e.term}` | {e.version} | {_levels(e)} | {_cell(e.description)} |"
        )
    return rows


def skill_vocabulary_section() -> str:
    """The markdown between the markers: one table per kind, then the methods by aspect."""
    out = [
        "## Vocabulary (generated)",
        "",
        "Every name a scene may use, with its version and the spectrum levels it "
        "accepts ((a) typed, (b-name) a registered name, (b-llm) a description "
        "resolved before the IR, (c) a checked goal). `an.semantic.vocabulary()` "
        "returns the same list as data; easings: `an.timing.easing.easing_entries()`.",
    ]
    for kind, heading in SKILL_KINDS:
        found = entries(kind=kind)
        if found:
            out += ["", f"### {heading}", "", *_table(found)]
    method_rows: list[str] = []
    for a in aspects():
        for m in methods_of(a.name):
            if not isinstance(m, Method):
                continue
            needs = ", ".join(f"`{r}`" for r in m.requires) or "nothing"
            method_rows.append(
                f"| {a.name} | `{m.id}` | `{m.term}` | {m.version} | {needs} | {_cell(m.description)} |"
            )
    if method_rows:
        out += [
            "",
            "### Methods, by aspect",
            "",
            "Default chains: "
            + "; ".join(
                f"**{a.name}** " + " → ".join(f"`{c}`" for c in a.chain)
                for a in aspects()
            )
            + ". `an character capabilities <name>` says which apply to a character and what is missing for the rest.",
            "",
            "| Aspect | Method | Spelled | Version | Requires | What it is |",
            "|---|---|---|---|---|---|",
            *method_rows,
        ]
    return "\n".join(out)


def replace_section(text: str, section: str) -> str:
    """``text`` with the block between the markers replaced by ``section``.

    >>> replace_section(f"a\\n{BEGIN_MARKER}\\nold\\n{END_MARKER}\\nb", "new").splitlines()[2]
    'new'
    """
    start = text.index(BEGIN_MARKER) + len(BEGIN_MARKER)
    end = text.index(END_MARKER)
    return text[:start] + "\n" + section + "\n" + text[end:]


def current_section(text: str) -> str:
    """The block between the markers, as written."""
    start = text.index(BEGIN_MARKER) + len(BEGIN_MARKER)
    return text[start : text.index(END_MARKER)].strip("\n")


def main(argv: list[str] | None = None) -> int:
    """``--write PATH`` rewrites the section in place; ``--check PATH`` exits 1 when stale."""
    from an.genres import load

    args = list(sys.argv[1:] if argv is None else argv)
    if len(args) != 2 or args[0] not in ("--write", "--check"):
        print("usage: python -m an.semantic.docs (--write|--check) SKILL.md")
        return 2
    load()
    path = Path(args[1])
    text = path.read_text(encoding="utf-8")
    fresh = skill_vocabulary_section()
    if args[0] == "--check":
        stale = current_section(text) != fresh
        print("stale" if stale else "up to date")
        return int(stale)
    path.write_text(replace_section(text, fresh), encoding="utf-8")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
