"""The vocabulary as a published, code-free contract file: ``an/data/timing/vocabulary.json``.

ADR 0006 decision 2 (and an#261): the vocabulary registry
(:mod:`an.semantic.registry`) is authored in ``an``; any other engine — the
TypeScript ``previz``, ``shaping``, the ``burns`` port — reads it as data. This
module is the exporter, in the pattern of :mod:`an.timing.contract`: a builder
(:func:`build_vocabulary`), a writer (:func:`write_vocabulary`), a drift check
(:func:`vocabulary_drift`) and a ``write``/``check`` command line::

    python -m an.semantic.export write
    python -m an.semantic.export check

What it carries, per entry: ``id``, ``kind``, ``name`` (how a document spells
it), ``version``, ``title``, ``description``, ``levels`` (the spectrum levels it
accepts), ``params`` (a JSON Schema object with defaults), ``requires`` (the
ADR 0002 requirement terms) and, where the entry has them, ``usage``,
``examples``, ``aspects`` and (methods) ``aspect`` and ``remedies``. Never
``expand``: no code leaves ``an``. Camera moves are entries of kind
``camera_move`` whose ``params.path`` lies in a ``view_space`` entry
(``view.framing2d``, ``view.orbit3d``), so an engine reads a move once and
lowers it through the space it affords.

**Only ``an``'s own entries** (``owner="an"``) are exported, so the file does
not depend on which genres happen to be loaded, and an installed genre never
edits it. Publishing a genre's entries is a deliberate act: pass ``owners=`` and
say so (ADR 0006, Risks: the package is public).

>>> doc = build_vocabulary()
>>> doc["version"], doc["owners"]
(1, ['an'])
>>> by_id = {e["id"]: e for e in doc["entries"]}
>>> by_id["camera.push_in"]["params"]["properties"]["path"]["default"][-1]["zoom"] > 1
True
>>> "expand" in by_id["camera.push_in"], by_id["view.framing2d"]["kind"]
(False, 'view_space')
"""

from __future__ import annotations

import json
import sys
from collections.abc import Iterable
from pathlib import Path
from typing import Any

__all__ = [
    "VOCABULARY_FILE",
    "VOCABULARY_FORMAT_VERSION",
    "build_vocabulary",
    "vocabulary_drift",
    "write_vocabulary",
]

#: The vocabulary export's file name, beside the timing contract's files.
VOCABULARY_FILE: str = "vocabulary.json"
#: The shape of the file (not of its entries, which carry their own versions).
VOCABULARY_FORMAT_VERSION: int = 1
#: Whose entries are published unless a caller says otherwise.
DFLT_OWNERS: tuple[str, ...] = ("an",)
#: Where the file lives: with the timing contract's, inside the package so it ships.
CONTRACT_DIR: Path = Path(__file__).resolve().parents[1] / "data" / "timing"


def build_vocabulary(*, owners: Iterable[str] = DFLT_OWNERS) -> dict[str, Any]:
    """The export document: every entry ``owners`` registered, as data, sorted by id."""
    from an.semantic.entries import LEVELS
    from an.semantic.registry import entries

    owners = tuple(owners)
    selected = [e for owner in owners for e in entries(owner=owner)]
    return {
        "version": VOCABULARY_FORMAT_VERSION,
        "description": (
            "The vocabulary registry of `an`, as data: every name a structured "
            "animation document may spell, versioned, with its params as JSON Schema. "
            "Generated by `python -m an.semantic.export write`; never hand-edited."
        ),
        "levels": list(LEVELS),
        "owners": sorted(owners),
        "entries": sorted((e.to_json() for e in selected), key=lambda e: e["id"]),
    }


def _dumps(obj: Any) -> str:
    from an.timing.contract import dumps  # the one committed-text format

    return dumps(obj)


def write_vocabulary(directory: Path = CONTRACT_DIR) -> Path:
    """Regenerate ``vocabulary.json`` under ``directory``."""
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / VOCABULARY_FILE
    path.write_text(_dumps(build_vocabulary()), encoding="utf-8")
    return path


def vocabulary_drift(directory: Path = CONTRACT_DIR) -> list[str]:
    """How the committed ``vocabulary.json`` differs from what the registry generates (empty: none)."""
    path = directory / VOCABULARY_FILE
    if not path.exists():
        return [f"{VOCABULARY_FILE}: missing"]
    from an.timing.contract import values_close

    committed = json.loads(path.read_text(encoding="utf-8"))
    # The contract's own comparison: a float may differ in its last bit across
    # platforms' maths libraries; everything else must match exactly.
    if not values_close(committed, json.loads(_dumps(build_vocabulary()))):
        return [f"{VOCABULARY_FILE}: differs from what the registry generates"]
    return []


def main(argv: list[str] | None = None) -> int:
    """``python -m an.semantic.export [write|check]``."""
    args = sys.argv[1:] if argv is None else argv
    command = args[0] if args else "check"
    if command == "write":
        print(f"wrote {write_vocabulary().name}")
        return 0
    if command == "check":
        problems = vocabulary_drift()
        for line in problems:
            print(line)
        return 1 if problems else 0
    print(f"usage: python -m an.semantic.export [write|check]; got {command!r}")
    return 2


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
